{% set name = "static" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/static-{{ version }}.tar.gz
  sha256: 4a2dfc165c9242304b117e80fb200eb62742a1c51dbaac50451419dccee76395

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pystache
    - setuptools

test:
  imports:
    - static
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/lukearno/static
  summary: Serve static or templated content via WSGI or stand-alone.
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

about:
  home: https://github.com/lukearno/static
  license: MIT
  # https://github.com/lukearno/static/issues/22
  # license_file:
  summary: 'A really simple WSGI way to serve static (or mixed) content.'

extra:
  recipe-maintainers:
    - kwilcox
