travis:
  secure:
    BINSTAR_TOKEN: DmAvKKy/exTFekWT9A6qNztjPpWM5cLANQmpznOU0GJYg7nB3bo8q6+Bvz2LGR/uzISuCVn9dWyCUj0+VactU9pZ86vWNGXHCvOEzG5qUpj/2Zdfcz3Tm1atbgHOjhM4hITP8QtNdadJxXC0+cSDtvxEog/GRaNGVj1OX3bBnsVKi+SaEBNP7e9oMA/Djghd5LJBKfT9KaYjNKtdhmZa28JRANGhevsWdD9XP/GjEsze7AfDpcU+6vsQj/ITpR+H5FTOmhPri59vMlcavsTPs4hmpMJCUq/gtYnVnCI/j8HYBP1T8wBxvhnejDlasFV6SfwCJ/c8SeBGNrNWQMWC1UZH2oGZ2GabrLDGXN0xfu2R9b6E7BHFN/W8IHXhrgQHS2FscdHRyD7RhHBdDlNnd+tMv8eSJLxZB3wVUf62cvdcnc1btiBqu1J1s034pPudVWaJMExJvWYD2azlNtjNDIcEHFgNuKHIRxJrT5xVH2EJElnDdW1YJYJrcRZ0fl6qp7QVgtI3eBQboBDKq+it31Evp1gFCiCJg2qAkvDDjh49nDdu6kMeeXSXhAEZJFwBH8PJeY4/Yzj6836wOk4eaE4/5nMQ30eNNbDSj67kTzcwClDnmAbPGId2KOe3w8d7F2oSFxCWmSZm6+ZfUpZawFrjuwPPQU9/99TVckYcTJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
