travis:
  secure:
    BINSTAR_TOKEN: lTCm7X4RL/VH67frowdsBKkIrcWR8cm4p9X6nn84ofVMgLIARZmGW1E2PN86m46bwEN1NSPT1Ap2Yi2nNjnq44XxqDsHj80khbT0XNVDOeuPuDrHVnGAHOHkKYX6Fa8UTqjWMwowQ0W8u5uv3jB+URVW+Yhlg1nUJ5uwEUpJp15No8LVgjmwHjqlcNJxZZrNfsE5mPAzacZtre3S2Z3caFH1JSxC1EJDD4PnfM1PzZHu7LF7gIgKfZezYU23FvOmuDrxku5Kf+q/F6f2EKlK2o2pf4qvq/qNQozAgqn0jlkMc4cAqUazb1ZdLGgkQ8g1aHtakeJL9I/YaHX0rE/EroieTvBb0kzCkne96b2RkhwxUJSRLoCie79HAlCs1afOLtV4q89dGmEPoeEMarY5Dc7n5AXtJqdrHoyPWltthggWqRkOUde30XjBQdBNyYVJHbV1N2gxxp+XiPqmGGNfuQudRupY7Qa+JAzo6wlndevAAM6K85JKHY2r6q3RMfz/mk1EraqNFj5aiVs3Ozue9agNSpIk+SIzfHZUVrpeG89g28exQ3l3tiZkJ+Tg9ELxPKieC3tOwXkthcXiWGlITpjWe0ljiS5CE0mQzSOkbO4PgiQME9hzPyqofpwVjx3hll2NlyQYT2uarmqqsb2RNS/LdcssEcu0Ga+dAX1LjV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
